Homework is done
v-antanovich/automation-practice-js pull request #70
Opened 2023-07-10 14:11 UTC by vladsheverda7

2023-07-10 15:05 UTC, Hanna10Domnich requested changes

2023-07-10 15:05 UTC, Hanna10Domnich commented on community/v.sheverda/objects-and-functions/objects_functions.js
> +  let {
let {programmingLangs} = plan.skills;

2023-07-11 08:09 UTC, vladsheverda7 commented on community/v.sheverda/objects-and-functions/objects_functions.js
> +  let {
fixed

2023-07-11 13:57 UTC, v-antanovich approved these changes
You’ve got it made

2023-07-11 13:58 UTC, merged