Add 5 task Functions
v-antanovich/automation-practice-js pull request #72
Opened 2023-07-12 08:17 UTC by SavichGV

2023-07-13 08:22 UTC, Hanna10Domnich requested changes

2023-07-13 08:22 UTC, Hanna10Domnich commented on community/h.savich/5_Functions.js
> +    let age = plan.age;
const {age} = plan;

2023-07-13 08:22 UTC, Hanna10Domnich commented on community/h.savich/5_Functions.js
> +//3 Создайте метод showAgeAndLangs внутри объекта personalPlanPeter. При его вызове метод будет принимать в себя объект и возвращать строку в нужном виде.
перенеси пожалуйста свою функцию в объект, в условии написано что необходимо создать метод уже в существующем объекте а не создавать новый объект

2023-09-04 16:59 UTC, SavichGV commented on community/h.savich/5_Functions.js
> +    let age = plan.age;
почему это важно?

2023-09-04 17:05 UTC, SavichGV commented on community/h.savich/5_Functions.js
> +//3 Создайте метод showAgeAndLangs внутри объекта personalPlanPeter. При его вызове метод будет принимать в себя объект и возвращать строку в нужном виде.
fixed

2023-09-07 08:53 UTC, merged